[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'simple-filter-xml'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'This is a simple Filter/XML Transform Application Service'
Timeout = 5000

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'

[MessageBus]
Type = 'zero'
    [MessageBus.PublishHost]
        Host = '*'
        Port = 5564
        Protocol = 'tcp'
    [MessageBus.SubscribeHost]
        Host = 'localhost'
        Port = 5563
        Protocol = 'tcp'

[Logging]
EnableRemote = false
File = '/edgex/logs/simple-filter-xml.log'

# [Binding]
#  Type="messagebus"
#  SubscribeTopic="events"
#  PublishTopic="somewhere"
 
[Binding]
Type="http"

[ApplicationSettings]
ApplicationName = "simple-filter-xml"
